// Auto-generated by: npx supabase gen types typescript --project-id YOUR_ID > types/database.ts
// Run this command after setting up your Supabase project to replace this placeholder.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string
          slug: string
          name_ka: string
          name_ru: string
          name_en: string
          cover_url: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name_ka: string
          name_ru: string
          name_en: string
          cover_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name_ka?: string
          name_ru?: string
          name_en?: string
          cover_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      products: {
        Row: {
          id: string
          slug: string
          category_id: string | null
          name_ka: string
          name_ru: string
          name_en: string
          description_ka: string | null
          description_ru: string | null
          description_en: string | null
          price: number
          sizes: string[]
          colors: string[]
          images: string[]
          is_active: boolean
          is_featured: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          category_id?: string | null
          name_ka: string
          name_ru: string
          name_en: string
          description_ka?: string | null
          description_ru?: string | null
          description_en?: string | null
          price: number
          sizes?: string[]
          colors?: string[]
          images?: string[]
          is_active?: boolean
          is_featured?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          category_id?: string | null
          name_ka?: string
          name_ru?: string
          name_en?: string
          description_ka?: string | null
          description_ru?: string | null
          description_en?: string | null
          price?: number
          sizes?: string[]
          colors?: string[]
          images?: string[]
          is_active?: boolean
          is_featured?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          }
        ]
      }
      bundles: {
        Row: {
          id: string
          slug: string
          name_ka: string
          name_ru: string
          name_en: string
          description_ka: string | null
          description_ru: string | null
          description_en: string | null
          price: number
          original_price: number | null
          cover_url: string | null
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name_ka: string
          name_ru: string
          name_en: string
          description_ka?: string | null
          description_ru?: string | null
          description_en?: string | null
          price: number
          original_price?: number | null
          cover_url?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name_ka?: string
          name_ru?: string
          name_en?: string
          description_ka?: string | null
          description_ru?: string | null
          description_en?: string | null
          price?: number
          original_price?: number | null
          cover_url?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      bundle_products: {
        Row: {
          bundle_id: string
          product_id: string
          quantity: number
        }
        Insert: {
          bundle_id: string
          product_id: string
          quantity?: number
        }
        Update: {
          bundle_id?: string
          product_id?: string
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: "bundle_products_bundle_id_fkey"
            columns: ["bundle_id"]
            isOneToOne: false
            referencedRelation: "bundles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bundle_products_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          }
        ]
      }
      orders: {
        Row: {
          id: string
          customer_name: string | null
          customer_phone: string | null
          items: Json
          total_price: number | null
          status: 'new' | 'processing' | 'completed' | 'cancelled'
          notes: string | null
          whatsapp_sent_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          customer_name?: string | null
          customer_phone?: string | null
          items: Json
          total_price?: number | null
          status?: 'new' | 'processing' | 'completed' | 'cancelled'
          notes?: string | null
          whatsapp_sent_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          customer_name?: string | null
          customer_phone?: string | null
          items?: Json
          total_price?: number | null
          status?: 'new' | 'processing' | 'completed' | 'cancelled'
          notes?: string | null
          whatsapp_sent_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      order_status: 'new' | 'processing' | 'completed' | 'cancelled'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
